# Generated by Django 4.1.3 on 2022-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=150, verbose_name='카테고리'),
        ),
    ]
