# Generated by Django 4.1.3 on 2022-11-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_article_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="likes",
            new_name="like",
        ),
    ]
