# Generated by Django 4.1.3 on 2022-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('eccv16/composition_vii.t7', 'eccv16/composition_vii.t7'), ('eccv16/la_muse.t7', 'eccv16/la_muse.t7'), ('eccv16/starry_night.t7', 'eccv16/starry_night.t7'), ('eccv16/the_wave.t7', 'eccv16/the_wave.t7'), ('instance_norm/candy.t7', 'instance_norm/candy.t7'), ('instance_norm/feathers.t7', 'instance_norm/feathers.t7'), ('instance_norm/la_muse.t7', 'instance_norm/la_muse.t7'), ('instance_norm/mosaic.t7', 'instance_norm/mosaic.t7'), ('instance_norm/starry_night.t7', 'instance_norm/starry_night.t7'), ('instance_norm/udnie.t7', 'instance_norm/udnie.t7')], max_length=150, verbose_name='카테고리'),
        ),
    ]
