# Generated by Django 4.1.3 on 2022-11-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('eccv16/composition_vii.t7', 'EC_컴포지션'), ('eccv16/la_muse.t7', 'EC_뮤즈'), ('eccv16/starry_night.t7', 'EC_나이트'), ('eccv16/the_wave.t7', 'EC_웨이브'), ('instance_norm/candy.t7', 'IN_캔디'), ('instance_norm/feathers.t7', 'IN_패덜'), ('instance_norm/la_muse.t7', 'IN_뮤즈'), ('instance_norm/mosaic.t7', 'IN_모자이크'), ('instance_norm/starry_night.t7', 'IN_나이트'), ('instance_norm/udnie.t7', 'IN_우드네')], max_length=150, verbose_name='카테고리'),
        ),
    ]
