# Generated by Django 4.1.3 on 2022-11-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_rename_likes_article_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="like",
            new_name="likes",
        ),
    ]
