# Generated by Django 4.1.3 on 2022-11-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300, verbose_name='댓글'),
        ),
    ]
